"""auto_llm_20260409_144715

Revision ID: 091a29d06d29
Revises: 93cfffcf950d
Create Date: 2026-04-09 14:47:16.326096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091a29d06d29'
down_revision: Union[str, None] = '93cfffcf950d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_context_tokens', sa.Integer(), server_default=sa.text('(200000)'), nullable=False))
        batch_op.add_column(sa.Column('max_output_tokens', sa.Integer(), server_default=sa.text('(64000)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_column('max_output_tokens')
        batch_op.drop_column('max_context_tokens')

    # ### end Alembic commands ###
