"""add_usage_hot_indexes

Revision ID: 138002b3b8ce
Revises: ad9633088556
Create Date: 2026-06-14 13:12:48.215984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138002b3b8ce'
down_revision: Union[str, None] = 'ad9633088556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.create_index('idx_usage_user_context', ['user_id', 'context_key'], unique=False)
        batch_op.create_index('idx_usage_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_usage_user_model_created', ['user_id', 'model_id', 'created_at'], unique=False)
        batch_op.create_index('idx_usage_user_scope_created', ['user_id', 'quota_scope', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_usage_user_scope_created')
        batch_op.drop_index('idx_usage_user_model_created')
        batch_op.drop_index('idx_usage_user_created')
        batch_op.drop_index('idx_usage_user_context')

    # ### end Alembic commands ###
