"""model_input_output_modalities

Revision ID: 2af91355fef0
Revises: 98c95f475ac9
Create Date: 2026-07-10 21:05:50.144259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af91355fef0'
down_revision: Union[str, None] = '98c95f475ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_modalities', sa.String(length=256), server_default=sa.text('\'["text"]\''), nullable=False))
        batch_op.add_column(sa.Column('output_modalities', sa.String(length=256), server_default=sa.text('\'["text"]\''), nullable=False))
        batch_op.drop_index(batch_op.f('ix_llm_platform_models_is_embedding'))
        batch_op.drop_column('capabilities')
        batch_op.drop_column('is_embedding')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_embedding', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('capabilities', sa.VARCHAR(length=512), nullable=True))
        batch_op.create_index(batch_op.f('ix_llm_platform_models_is_embedding'), ['is_embedding'], unique=False)
        batch_op.drop_column('output_modalities')
        batch_op.drop_column('input_modalities')

    # ### end Alembic commands ###
