"""add_model_capabilities

Revision ID: 4d8a1025c46c
Revises: f36d19a34faf
Create Date: 2026-07-02 17:04:19.486708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8a1025c46c'
down_revision: Union[str, None] = 'f36d19a34faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capabilities', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_column('capabilities')

    # ### end Alembic commands ###
