"""auto_llm_20260207_225326

Revision ID: 5bf87038434c
Revises: 4a12a8844ed3
Create Date: 2026-02-07 22:53:35.414761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf87038434c'
down_revision: Union[str, None] = '4a12a8844ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_column('uv')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uv', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
