"""auto_llm_20260320_020844

Revision ID: 6191d6d71cec
Revises: a3e950d6225b
Create Date: 2026-03-20 02:14:27.939413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6191d6d71cec'
down_revision: Union[str, None] = 'a3e950d6225b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_credit_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_credit_pricing_billing_scope'))
        batch_op.drop_index(batch_op.f('ix_model_credit_pricing_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_model_credit_pricing_model_id'))
        batch_op.drop_index(batch_op.f('ix_model_credit_pricing_platform_id'))

    op.drop_table('model_credit_pricing')
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_credit_price_per_million_tokens', sa.Integer(), nullable=True))

    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_credit_price_per_million_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_column('sys_credit_price_per_million_tokens')

    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_column('sys_credit_price_per_million_tokens')

    op.create_table('model_credit_pricing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('platform_id', sa.INTEGER(), nullable=False),
    sa.Column('model_id', sa.INTEGER(), nullable=False),
    sa.Column('billing_scope', sa.VARCHAR(length=32), nullable=False),
    sa.Column('request_base_cost', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('prompt_token_cost_per_1k', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('completion_token_cost_per_1k', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('is_enabled', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('remark', sa.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['llm_platform_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['llm_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'model_id', name=op.f('uq_model_credit_pricing_platform_model'))
    )
    with op.batch_alter_table('model_credit_pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_credit_pricing_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_credit_pricing_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_credit_pricing_is_enabled'), ['is_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_credit_pricing_billing_scope'), ['billing_scope'], unique=False)

    # ### end Alembic commands ###
