"""baseline_llm_20260430_013137

Revision ID: 63aa63f0d443
Revises: 
Create Date: 2026-04-30 01:31:37.497684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63aa63f0d443'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_model_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('usage_key', sa.String(length=64), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_name', name='uq_user_agent_binding')
    )
    with op.batch_alter_table('agent_model_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_model_bindings_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_model_bindings_user_id'), ['user_id'], unique=False)

    op.create_table('llm_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('is_sys', sa.Integer(), nullable=True),
    sa.Column('disable', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('sys_credit_balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_platforms_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_platforms_user_id'), ['user_id'], unique=False)

    op.create_table('redeem_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.Column('code_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redeem_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redeem_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_redeem_codes_code_type'), ['code_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_codes_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_codes_status'), ['status'], unique=False)

    op.create_table('user_credit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('billing_scope', sa.String(length=32), nullable=False),
    sa.Column('credit_balance', sa.Float(), nullable=False),
    sa.Column('credit_total_granted', sa.Float(), nullable=False),
    sa.Column('credit_total_used', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'billing_scope', name='uq_user_credit_account_user_scope')
    )
    with op.batch_alter_table('user_credit_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_credit_accounts_billing_scope'), ['billing_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_credit_accounts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_credit_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('user_quota_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('sys_paid_window_hours', sa.Integer(), nullable=True),
    sa.Column('sys_paid_window_token_limit', sa.Integer(), nullable=True),
    sa.Column('sys_paid_window_request_limit', sa.Integer(), nullable=True),
    sa.Column('sys_paid_total_token_limit', sa.Integer(), nullable=True),
    sa.Column('sys_paid_total_request_limit', sa.Integer(), nullable=True),
    sa.Column('self_paid_window_hours', sa.Integer(), nullable=True),
    sa.Column('self_paid_window_token_limit', sa.Integer(), nullable=True),
    sa.Column('self_paid_window_request_limit', sa.Integer(), nullable=True),
    sa.Column('self_paid_total_token_limit', sa.Integer(), nullable=True),
    sa.Column('self_paid_total_request_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_quota_policy')
    )
    with op.batch_alter_table('user_quota_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_quota_policies_user_id'), ['user_id'], unique=False)

    op.create_table('llm_platform_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('extra_body', sa.String(length=1024), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_context_tokens', sa.Integer(), server_default=sa.text('(200000)'), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), server_default=sa.text('(64000)'), nullable=False),
    sa.Column('sys_credit_input_price_per_million', sa.Float(), nullable=True),
    sa.Column('sys_credit_output_price_per_million', sa.Float(), nullable=True),
    sa.Column('disable', sa.Integer(), nullable=True),
    sa.Column('is_embedding', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['llm_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_platform_models_disable'), ['disable'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_platform_models_is_embedding'), ['is_embedding'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_platform_models_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_platform_models_platform_id'), ['platform_id'], unique=False)

    op.create_table('llm_sys_platform_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('disable', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['llm_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform_id', name='uq_sys_platform_key_user_platform')
    )
    with op.batch_alter_table('llm_sys_platform_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_sys_platform_keys_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_sys_platform_keys_user_id'), ['user_id'], unique=False)

    op.create_table('redeem_code_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redeem_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('delta_credit', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['redeem_code_id'], ['redeem_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redeem_code_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redeem_code_usages_redeem_code_id'), ['redeem_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_code_usages_used_at'), ['used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_code_usages_user_id'), ['user_id'], unique=False)

    op.create_table('model_usage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['llm_platform_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'model_id', name='uq_user_model_stats')
    )
    with op.batch_alter_table('model_usage_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_usage_stats_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_usage_stats_user_id'), ['user_id'], unique=False)

    op.create_table('usage_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=120), nullable=True),
    sa.Column('context_key', sa.String(length=255), nullable=True),
    sa.Column('quota_scope', sa.String(length=32), nullable=True),
    sa.Column('credit_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['llm_platform_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_log_entries_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_entries_credit_cost'), ['credit_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_entries_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_entries_quota_scope'), ['quota_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_entries_user_id'), ['user_id'], unique=False)

    op.create_table('user_embedding_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['llm_platform_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['llm_platforms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_embedding_selection')
    )
    with op.batch_alter_table('user_embedding_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_embedding_selections_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_embedding_selections_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_embedding_selections_user_id'), ['user_id'], unique=False)

    op.create_table('user_model_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('usage_key', sa.String(length=64), nullable=False),
    sa.Column('usage_label', sa.String(length=120), nullable=False),
    sa.Column('selected_platform_id', sa.Integer(), nullable=True),
    sa.Column('selected_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['selected_model_id'], ['llm_platform_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_platform_id'], ['llm_platforms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_key', name='uq_user_usage_key')
    )
    with op.batch_alter_table('user_model_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_model_usages_selected_model_id'), ['selected_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_model_usages_selected_platform_id'), ['selected_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_model_usages_usage_key'), ['usage_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_model_usages_user_id'), ['user_id'], unique=False)

    op.create_table('user_credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('billing_scope', sa.String(length=32), nullable=False),
    sa.Column('delta_credit', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('reason_type', sa.String(length=32), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('usage_log_id', sa.Integer(), nullable=True),
    sa.Column('operator_user_id', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['llm_platform_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['llm_platforms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usage_log_id'], ['usage_log_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_credit_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_credit_ledger_billing_scope'), ['billing_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_credit_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_credit_ledger_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_credit_ledger_operator_user_id'), ['operator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_credit_ledger_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_credit_ledger_reason_type'), ['reason_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_credit_ledger_usage_log_id'), ['usage_log_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_credit_ledger_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credit_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_credit_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_credit_ledger_usage_log_id'))
        batch_op.drop_index(batch_op.f('ix_user_credit_ledger_reason_type'))
        batch_op.drop_index(batch_op.f('ix_user_credit_ledger_platform_id'))
        batch_op.drop_index(batch_op.f('ix_user_credit_ledger_operator_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_credit_ledger_model_id'))
        batch_op.drop_index(batch_op.f('ix_user_credit_ledger_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_credit_ledger_billing_scope'))

    op.drop_table('user_credit_ledger')
    with op.batch_alter_table('user_model_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_model_usages_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_model_usages_usage_key'))
        batch_op.drop_index(batch_op.f('ix_user_model_usages_selected_platform_id'))
        batch_op.drop_index(batch_op.f('ix_user_model_usages_selected_model_id'))

    op.drop_table('user_model_usages')
    with op.batch_alter_table('user_embedding_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_embedding_selections_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_embedding_selections_platform_id'))
        batch_op.drop_index(batch_op.f('ix_user_embedding_selections_model_id'))

    op.drop_table('user_embedding_selections')
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_quota_scope'))
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_model_id'))
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_credit_cost'))
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_agent_name'))

    op.drop_table('usage_log_entries')
    with op.batch_alter_table('model_usage_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_usage_stats_user_id'))
        batch_op.drop_index(batch_op.f('ix_model_usage_stats_model_id'))

    op.drop_table('model_usage_stats')
    with op.batch_alter_table('redeem_code_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redeem_code_usages_user_id'))
        batch_op.drop_index(batch_op.f('ix_redeem_code_usages_used_at'))
        batch_op.drop_index(batch_op.f('ix_redeem_code_usages_redeem_code_id'))

    op.drop_table('redeem_code_usages')
    with op.batch_alter_table('llm_sys_platform_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_sys_platform_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_sys_platform_keys_platform_id'))

    op.drop_table('llm_sys_platform_keys')
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_platform_models_platform_id'))
        batch_op.drop_index(batch_op.f('ix_llm_platform_models_model_name'))
        batch_op.drop_index(batch_op.f('ix_llm_platform_models_is_embedding'))
        batch_op.drop_index(batch_op.f('ix_llm_platform_models_disable'))

    op.drop_table('llm_platform_models')
    with op.batch_alter_table('user_quota_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_quota_policies_user_id'))

    op.drop_table('user_quota_policies')
    with op.batch_alter_table('user_credit_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_credit_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_credit_accounts_status'))
        batch_op.drop_index(batch_op.f('ix_user_credit_accounts_billing_scope'))

    op.drop_table('user_credit_accounts')
    with op.batch_alter_table('redeem_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redeem_codes_status'))
        batch_op.drop_index(batch_op.f('ix_redeem_codes_created_by'))
        batch_op.drop_index(batch_op.f('ix_redeem_codes_created_at'))
        batch_op.drop_index(batch_op.f('ix_redeem_codes_code_type'))
        batch_op.drop_index(batch_op.f('ix_redeem_codes_code'))

    op.drop_table('redeem_codes')
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_platforms_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_platforms_name'))

    op.drop_table('llm_platforms')
    with op.batch_alter_table('agent_model_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_model_bindings_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_model_bindings_agent_name'))

    op.drop_table('agent_model_bindings')
    # ### end Alembic commands ###
