"""auto_llm_20260207_230228

Revision ID: 79aaf42d2c34
Revises: 5bf87038434c
Create Date: 2026-02-07 23:02:31.461246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79aaf42d2c34'
down_revision: Union[str, None] = '5bf87038434c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aaa', sa.Integer(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_column('aaa')

    # ### end Alembic commands ###
