"""add_redeem_code_tables

Revision ID: 805c2aaebae9
Revises: 091a29d06d29
Create Date: 2026-04-11 01:45:18.734978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '805c2aaebae9'
down_revision: Union[str, None] = '091a29d06d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redeem_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('credit_amount', sa.Integer(), nullable=False),
    sa.Column('code_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redeem_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redeem_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_redeem_codes_code_type'), ['code_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_codes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_codes_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_codes_status'), ['status'], unique=False)

    op.create_table('redeem_code_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redeem_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('delta_credit', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['redeem_code_id'], ['redeem_codes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('redeem_code_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redeem_code_usages_redeem_code_id'), ['redeem_code_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_code_usages_used_at'), ['used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_redeem_code_usages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redeem_code_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redeem_code_usages_user_id'))
        batch_op.drop_index(batch_op.f('ix_redeem_code_usages_used_at'))
        batch_op.drop_index(batch_op.f('ix_redeem_code_usages_redeem_code_id'))

    op.drop_table('redeem_code_usages')
    with op.batch_alter_table('redeem_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redeem_codes_status'))
        batch_op.drop_index(batch_op.f('ix_redeem_codes_created_by'))
        batch_op.drop_index(batch_op.f('ix_redeem_codes_created_at'))
        batch_op.drop_index(batch_op.f('ix_redeem_codes_code_type'))
        batch_op.drop_index(batch_op.f('ix_redeem_codes_code'))

    op.drop_table('redeem_codes')
    # ### end Alembic commands ###
