"""add_redeem_limits_and_credit_grants

Revision ID: 876688458b7d
Revises: ac9f582ba5ee
Create Date: 2026-07-30 12:39:56.927137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876688458b7d'
down_revision: Union[str, None] = 'ac9f582ba5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_grant_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_amount', sa.Float(), nullable=False),
    sa.Column('grant_scope', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_grant_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_grant_campaigns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_grant_campaigns_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_grant_campaigns_grant_scope'), ['grant_scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_grant_campaigns_status'), ['status'], unique=False)

    op.create_table('credit_grant_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('delta_credit', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['credit_grant_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_credit_grant_recipient_campaign_user')
    )
    with op.batch_alter_table('credit_grant_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_grant_recipients_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_grant_recipients_granted_at'), ['granted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_grant_recipients_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('redeem_code_usages', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_redeem_code_usage_code_user', ['redeem_code_id', 'user_id'])

    with op.batch_alter_table('redeem_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_redemptions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('redemption_count', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redeem_codes', schema=None) as batch_op:
        batch_op.drop_column('redemption_count')
        batch_op.drop_column('max_redemptions')

    with op.batch_alter_table('redeem_code_usages', schema=None) as batch_op:
        batch_op.drop_constraint('uq_redeem_code_usage_code_user', type_='unique')

    with op.batch_alter_table('credit_grant_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_grant_recipients_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_grant_recipients_granted_at'))
        batch_op.drop_index(batch_op.f('ix_credit_grant_recipients_campaign_id'))

    op.drop_table('credit_grant_recipients')
    with op.batch_alter_table('credit_grant_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_grant_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_credit_grant_campaigns_grant_scope'))
        batch_op.drop_index(batch_op.f('ix_credit_grant_campaigns_created_by'))
        batch_op.drop_index(batch_op.f('ix_credit_grant_campaigns_created_at'))

    op.drop_table('credit_grant_campaigns')
    # ### end Alembic commands ###
