"""baseline_llm_20260207_231545

Revision ID: 880160c0d9da
Revises: 
Create Date: 2026-02-07 23:15:47.132144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880160c0d9da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_model_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('usage_key', sa.String(length=64), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_name', name='uq_user_agent_binding')
    )
    with op.batch_alter_table('agent_model_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_model_bindings_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_model_bindings_user_id'), ['user_id'], unique=False)

    op.create_table('llm_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('is_sys', sa.Integer(), nullable=True),
    sa.Column('disable', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_platforms_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_platforms_user_id'), ['user_id'], unique=False)

    op.create_table('llm_platform_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('extra_body', sa.String(length=1024), nullable=True),
    sa.Column('is_embedding', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['llm_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_platform_models_is_embedding'), ['is_embedding'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_platform_models_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_platform_models_platform_id'), ['platform_id'], unique=False)

    op.create_table('llm_sys_platform_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('disable', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['llm_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform_id', name='uq_sys_platform_key_user_platform')
    )
    with op.batch_alter_table('llm_sys_platform_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_sys_platform_keys_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_sys_platform_keys_user_id'), ['user_id'], unique=False)

    op.create_table('model_usage_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['llm_platform_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'model_id', name='uq_user_model_stats')
    )
    with op.batch_alter_table('model_usage_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_usage_stats_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_usage_stats_user_id'), ['user_id'], unique=False)

    op.create_table('usage_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('success', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=120), nullable=True),
    sa.Column('context_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['llm_platform_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_log_entries_agent_name'), ['agent_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_entries_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_entries_user_id'), ['user_id'], unique=False)

    op.create_table('user_embedding_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['llm_platform_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['llm_platforms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_embedding_selection')
    )
    with op.batch_alter_table('user_embedding_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_embedding_selections_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_embedding_selections_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_embedding_selections_user_id'), ['user_id'], unique=False)

    op.create_table('user_model_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('usage_key', sa.String(length=64), nullable=False),
    sa.Column('usage_label', sa.String(length=120), nullable=False),
    sa.Column('selected_platform_id', sa.Integer(), nullable=True),
    sa.Column('selected_model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['selected_model_id'], ['llm_platform_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['selected_platform_id'], ['llm_platforms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_key', name='uq_user_usage_key')
    )
    with op.batch_alter_table('user_model_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_model_usages_selected_model_id'), ['selected_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_model_usages_selected_platform_id'), ['selected_platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_model_usages_usage_key'), ['usage_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_model_usages_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_model_usages_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_model_usages_usage_key'))
        batch_op.drop_index(batch_op.f('ix_user_model_usages_selected_platform_id'))
        batch_op.drop_index(batch_op.f('ix_user_model_usages_selected_model_id'))

    op.drop_table('user_model_usages')
    with op.batch_alter_table('user_embedding_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_embedding_selections_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_embedding_selections_platform_id'))
        batch_op.drop_index(batch_op.f('ix_user_embedding_selections_model_id'))

    op.drop_table('user_embedding_selections')
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_model_id'))
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_agent_name'))

    op.drop_table('usage_log_entries')
    with op.batch_alter_table('model_usage_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_usage_stats_user_id'))
        batch_op.drop_index(batch_op.f('ix_model_usage_stats_model_id'))

    op.drop_table('model_usage_stats')
    with op.batch_alter_table('llm_sys_platform_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_sys_platform_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_sys_platform_keys_platform_id'))

    op.drop_table('llm_sys_platform_keys')
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_platform_models_platform_id'))
        batch_op.drop_index(batch_op.f('ix_llm_platform_models_model_name'))
        batch_op.drop_index(batch_op.f('ix_llm_platform_models_is_embedding'))

    op.drop_table('llm_platform_models')
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_platforms_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_platforms_name'))

    op.drop_table('llm_platforms')
    with op.batch_alter_table('agent_model_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_model_bindings_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_model_bindings_agent_name'))

    op.drop_table('agent_model_bindings')
    # ### end Alembic commands ###
