"""auto_llm_20260324_103646

Revision ID: 93cfffcf950d
Revises: b4c89f859f8e
Create Date: 2026-03-24 10:36:52.239818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93cfffcf950d'
down_revision: Union[str, None] = 'b4c89f859f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sys_credit_price_per_million_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disable', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_llm_platform_models_disable'), ['disable'], unique=False)

    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sys_credit_price_per_million_tokens', sa.Integer(), nullable=True))

    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_scope', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('credit_cost', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_usage_log_entries_credit_cost'), ['credit_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_log_entries_quota_scope'), ['quota_scope'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_quota_scope'))
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_credit_cost'))
        batch_op.drop_column('credit_cost')
        batch_op.drop_column('quota_scope')

    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_column('sys_credit_price_per_million_tokens')
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_platform_models_disable'))
        batch_op.drop_column('sort_order')
        batch_op.drop_column('disable')
        batch_op.drop_column('sys_credit_price_per_million_tokens')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
