"""add_image_generation_adapter

Revision ID: 98c95f475ac9
Revises: 4d8a1025c46c
Create Date: 2026-07-02 23:42:41.147487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c95f475ac9'
down_revision: Union[str, None] = '4d8a1025c46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_generation_adapter', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_column('image_generation_adapter')

    # ### end Alembic commands ###
