"""add_cached_prompt_tokens_to_usage_log

Revision ID: 9cec812a7335
Revises: 63aa63f0d443
Create Date: 2026-06-02 00:56:49.139245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cec812a7335'
down_revision: Union[str, None] = '63aa63f0d443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_prompt_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.drop_column('cached_prompt_tokens')

    # ### end Alembic commands ###
