"""auto_llm_20260319_012103

Revision ID: a3e950d6225b
Revises: b7c3e4f5a6d8
Create Date: 2026-03-19 01:21:06.271471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e950d6225b'
down_revision: Union[str, None] = 'b7c3e4f5a6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.alter_column('disable',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_scope', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_usage_log_entries_quota_scope'), ['quota_scope'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_log_entries_quota_scope'))
        batch_op.drop_column('quota_scope')

    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('disable',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
