"""add_search_provider_user_configs

Revision ID: ac9f582ba5ee
Revises: 2af91355fef0
Create Date: 2026-07-23 22:16:54.020437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9f582ba5ee'
down_revision: Union[str, None] = '2af91355fef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_provider_user_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('api_key', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_search_provider_user_provider')
    )
    with op.batch_alter_table('search_provider_user_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_provider_user_configs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_provider_user_configs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_provider_user_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_provider_user_configs_user_id'))
        batch_op.drop_index(batch_op.f('ix_search_provider_user_configs_provider'))

    op.drop_table('search_provider_user_configs')
    # ### end Alembic commands ###
