"""add_cached_input_credit_price

Revision ID: ad9633088556
Revises: d845e7ccf9be
Create Date: 2026-06-13 01:02:57.128079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9633088556'
down_revision: Union[str, None] = 'd845e7ccf9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_credit_cached_input_price_per_million', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_column('sys_credit_cached_input_price_per_million')

    # ### end Alembic commands ###
