"""auto_llm_20260207_014647

Revision ID: b3ec33729140
Revises: cce68f0d38eb
Create Date: 2026-02-07 01:46:50.233354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ec33729140'
down_revision: Union[str, None] = 'cce68f0d38eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field_v2', sa.String(length=50), nullable=True))
        batch_op.drop_column('test_field_v1')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field_v1', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('test_field_v2')

    # ### end Alembic commands ###
