"""auto_llm_20260207_015035

Revision ID: c044443ff845
Revises: b3ec33729140
Create Date: 2026-02-07 01:50:37.600157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c044443ff845'
down_revision: Union[str, None] = 'b3ec33729140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_column('test_field_v2')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field_v2', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
