"""auto_llm_20260207_014541

Revision ID: cce68f0d38eb
Revises: da12830110e6
Create Date: 2026-02-07 01:45:43.674742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce68f0d38eb'
down_revision: Union[str, None] = 'da12830110e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field_v1', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_column('test_field_v1')

    # ### end Alembic commands ###
