"""add_usage_cache_source_fields

Revision ID: d845e7ccf9be
Revises: 9cec812a7335
Create Date: 2026-06-12 23:12:17.694022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd845e7ccf9be'
down_revision: Union[str, None] = '9cec812a7335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cache_miss_prompt_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('usage_source', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('cache_source', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_log_entries', schema=None) as batch_op:
        batch_op.drop_column('cache_source')
        batch_op.drop_column('usage_source')
        batch_op.drop_column('cache_miss_prompt_tokens')

    # ### end Alembic commands ###
