"""auto_llm_20260206_040307

Revision ID: da12830110e6
Revises: 
Create Date: 2026-02-06 04:03:09.228300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da12830110e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('llm',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
