"""add_platform_key_identity

Revision ID: e3d042c824d9
Revises: 876688458b7d
Create Date: 2026-08-19 01:06:26.714822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d042c824d9'
down_revision: Union[str, None] = '876688458b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_key', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_llm_platforms_platform_key'), ['platform_key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_platforms_platform_key'))
        batch_op.drop_column('platform_key')

    # ### end Alembic commands ###
