"""auto_llm_20260207_160137

Revision ID: f352b6152ad8
Revises: dfcb0958c1df
Create Date: 2026-02-07 16:01:42.651780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f352b6152ad8'
down_revision: Union[str, None] = 'dfcb0958c1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_column('num')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
