"""add platform recharge url

Revision ID: f36d19a34faf
Revises: 138002b3b8ce
Create Date: 2026-06-23 12:14:08.945969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36d19a34faf'
down_revision: Union[str, None] = '138002b3b8ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recharge_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_column('recharge_url')

    # ### end Alembic commands ###
