"""auto_llm_20260412_031832

Revision ID: ff19691a6f79
Revises: 805c2aaebae9
Create Date: 2026-04-12 03:21:37.605421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff19691a6f79'
down_revision: Union[str, None] = '805c2aaebae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.drop_column('sys_credit_price_per_million_tokens')

    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.drop_column('sys_credit_output_price_per_million')
        batch_op.drop_column('sys_credit_price_per_million_tokens')
        batch_op.drop_column('sys_credit_input_price_per_million')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_credit_input_price_per_million', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sys_credit_price_per_million_tokens', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sys_credit_output_price_per_million', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('llm_platform_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_credit_price_per_million_tokens', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
