from typing import Any
from llm.agen_matchbox import matchbox
from llm.agen_matchbox.reasoning_compat import PrefixReasoningStreamParser
from agents.agent_utils import load_prompt, build_length_hint_str, SparkAgentExecutor
from agents.prompt_layout import build_prompt_messages
from .communication import SparkBaseAgent

class MuseAgent(SparkBaseAgent, SparkAgentExecutor):
    def __init__(self, user_id, project_name: str = ""):
        super().__init__(agent_id="agent_muse", user_id=user_id, project_name=project_name)
        self.llm = matchbox().get_user_llm(str(user_id), agent_name="agent_muse")

    def _get_tool_prompt_references(self) -> dict[str, list[dict]]:
        """把灵感扩展的结构化产出规范绑定到落盘工具。

        三态协议（详见 AGENTS.md §4.5）：
        - 专有工作模式（expand_inspiration）直接读 yaml.system 下的 7 条结构化规范；
        - 用户交互 / 导演委派模式走 chat_stream，调用 rewrite_inspiration 时，
          tool reference 机制会自动把 yaml.system 附加到工具描述后，保证 LLM
          看到同一份产出规范。避免在 pipeline_system 里再抄一份。
        """
        return {
            "rewrite_inspiration": [{"field": "system"}],
        }

    def _get_tool_prompt_reference_values(self) -> dict[str, dict[str, str]]:
        """为 tool reference 里的 yaml.system 占位符提供对话/委派场景下的默认填充。

        手动模式会从 expand_inspiration() 传入真实值；这里仅为 chat/pipeline 模式
        提供占位替换，避免 LLM 看到字面 `{style_hint}`。
        """
        return {
            "__root__": {
                "style_hint": "5. **风格倾向**：沿用用户原始指定或不限。",
                "genre_hint": "6. **题材方向**：沿用用户原始指定或不限。",
                "tone_hint": "7. **基调与流派**：沿用用户原始指定或不限。",
                "worldview_hint": "8. **世界规则**：沿用用户原始指定或不限。",
                "length_hint": "",
            }
        }

    def build_context(self, operation: str = "expand_inspiration", **kwargs) -> dict:
        """把灵感扩展请求整理成统一上下文，供不同入口复用。"""
        return {"operation": operation, **kwargs}

    def execute(self, context: dict, *args, **kwargs) -> Any:
        """按统一上下文执行灵感扩展或 Muse 对话。"""
        operation = context.get("operation") or "expand_inspiration"
        if operation == "chat":
            if kwargs.get("stream", False):
                return self.chat_stream(
                    user_message=context.get("user_message", ""),
                    history=context.get("history"),
                    active_context=context.get("active_context"),
                )
            return self.chat(
                user_message=context.get("user_message", ""),
                history=context.get("history"),
                active_context=context.get("active_context"),
            )
        return self.expand_inspiration(
            raw_input=context.get("raw_input", ""),
            style=context.get("style"),
            genres=context.get("genres"),
            tones=context.get("tones"),
            worldviews=context.get("worldviews"),
            length_hint=context.get("length_hint"),
            workspace_mode=context.get("workspace_mode"),
            story_tags=context.get("story_tags", ""),
        )

    def write_result(self, result: Any, *args, **kwargs) -> None:
        """
        根据入口差异把灵感结果写回现有条目或全局灵感库。

        `origin` 字段用于标记灵感条目的来源，方便后续做通知、筛选与兼容迁移：
        - `ui`：来自页面手动创建/手动扩写，不进入未读提醒
        - `mcp`：来自 MCP 捕获，会进入未读提醒与 MCP 列表逻辑
        - `legacy`：历史老数据补标记，表示该条目创建时系统还没有来源字段
        """
        from mcp_server.spark_inspiration.logic import save_inspiration, update_inspiration, current_user_id

        inspiration_id = kwargs.get("inspiration_id")
        source = kwargs.get("source", "")
        tags = kwargs.get("tags")
        origin = kwargs.get("origin", "ui")
        user_id = str(kwargs.get("user_id") or self.user_id)

        content = result if isinstance(result, str) else ""
        if not content:
            return None

        if inspiration_id:
            return update_inspiration(user_id, inspiration_id, {"content": content})

        token = current_user_id.set(user_id)
        try:
            return save_inspiration(
                source=source,
                content=content,
                tags=tags,
                origin=origin,
            )
        finally:
            current_user_id.reset(token)

    @staticmethod
    def generate_source_title(content: str, max_chars: int = 18) -> str:
        """从生成的灵感正文中提取前几字作为标题，加上 [AI] 前缀。"""
        import re
        text = (content or "").strip()
        lines = [l.strip() for l in text.splitlines() if l.strip()]
        first_line = lines[0] if lines else text
        first_line = re.sub(r"^\d+[\.\、]\s*[^：:]*[：:]\s*", "", first_line).strip()
        title = first_line[:max_chars]
        if len(first_line) > max_chars:
            title += "..."
        return f"[AI] {title}" if title else "[AI] This generated by SparkArc Muse."

    def expand_inspiration(self, raw_input: str = "", style: str = None,
                           genres: list = None, tones: list = None, worldviews: list = None, length_hint: str = None,
                           story_tags: str = "", workspace_mode: str | None = None):
        """将灵感碎片扩展为创意种子。raw_input 为空时 AI 自由创作。"""
        effective_input = (raw_input or "").strip() or (
            "请从空白开始创作一个原创灵感种子。"
            "先自主确定最适合的题材、形式与创作目标,再让关键选择彼此一致并可供下游继续发展。"
        )

        style_hint = "5.  **风格倾向**：不限。"
        if style:
            style_hint = f"5.  **风格倾向**：请以「{style}」风格为主导进行创作。"

        genre_hint = "6.  **题材方向**：不限。"
        if genres and len(genres) > 0:
            genre_hint = f"6.  **题材方向**：请围绕「{'、'.join(genres)}」题材展开构思。"

        tone_hint = "7.  **基调与流派**：不限。"
        if tones and len(tones) > 0:
            tone_hint = f"7.  **基调与流派**：请融入「{'、'.join(tones)}」的文学特质与氛围。"

        worldview_hint = "8.  **世界规则**：不限。"
        if worldviews and len(worldviews) > 0:
            worldview_hint = f"8.  **世界规则**：请基于「{'、'.join(worldviews)}」的世界规则构建背景。"

        length_hint_str = build_length_hint_str(length_hint, workspace_mode)

        prompts = load_prompt('muse', raw_input=effective_input,
                              style_hint=style_hint,
                              genre_hint=genre_hint,
                              tone_hint=tone_hint,
                              worldview_hint=worldview_hint,
                              length_hint=length_hint_str,
                              story_tags=story_tags or "")

        messages = build_prompt_messages(system_prompt=prompts['system'], user_prompt=prompts['user'])

        parser = PrefixReasoningStreamParser()
        for chunk in self.llm.stream(messages):
            content = getattr(chunk, "content", "")
            if not content:
                continue
            _, visible = parser.push(content)
            if visible:
                yield visible
        _, trailing_visible = parser.flush()
        if trailing_visible:
            yield trailing_visible


