"""initial_users

Revision ID: dba79ab7bc91
Revises: 
Create Date: 2026-01-28 00:41:18.648895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba79ab7bc91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('users',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
