"""auto_users_20260207_023328

Revision ID: 1e8bc8579a67
Revises: 0f88dabdc273
Create Date: 2026-02-07 02:33:29.411947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8bc8579a67'
down_revision: Union[str, None] = '0f88dabdc273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('final_test_col',
               existing_type=sa.Text(),
               new_column_name='final_test_renamed')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_test_col', sa.TEXT(), nullable=True))
        batch_op.drop_column('final_test_renamed')

    # ### end Alembic commands ###
