"""auto_users_20260207_021041

Revision ID: 1f693196e54a
Revises: 75105fb9c4ae
Create Date: 2026-02-07 02:10:42.756045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f693196e54a'
down_revision: Union[str, None] = '75105fb9c4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_data_v2', sa.String(length=50), nullable=True))
        batch_op.drop_column('test_data_v1')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_data_v1', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('test_data_v2')

    # ### end Alembic commands ###
