"""auto_users_20260207_014540

Revision ID: 49ce8de66335
Revises: d52ead50ed60
Create Date: 2026-02-07 01:45:41.067736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ce8de66335'
down_revision: Union[str, None] = 'd52ead50ed60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field_v1', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_field_v1')

    # ### end Alembic commands ###
