"""auto_users_20260207_015034

Revision ID: 49f29faf0ae9
Revises: a3411aa23ed5
Create Date: 2026-02-07 01:50:34.915364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f29faf0ae9'
down_revision: Union[str, None] = 'a3411aa23ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_field_v2')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field_v2', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
