"""auto_users_20260207_111421

Revision ID: 4fe099466f3c
Revises: 5ead413f1cd1
Create Date: 2026-02-07 11:14:21.854610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe099466f3c'
down_revision: Union[str, None] = '5ead413f1cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auto_test_renamed')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_test_renamed', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
