"""auto_users_20260207_013725

Revision ID: 642883ad2251
Revises: d93c5c8e685a
Create Date: 2026-02-07 01:37:26.828019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '642883ad2251'
down_revision: Union[str, None] = 'd93c5c8e685a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('debug_flag')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debug_flag', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
