"""add_chat_hot_indexes

Revision ID: 8ba76ae5c04c
Revises: dcf3957548a7
Create Date: 2026-06-14 13:12:35.899072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba76ae5c04c'
down_revision: Union[str, None] = 'dcf3957548a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_chat_session_id', ['user_id', 'project_name', 'agent_id', 'context_key', 'id'], unique=False)
        batch_op.create_index('idx_chat_session_timestamp', ['user_id', 'project_name', 'agent_id', 'context_key', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_chat_session_timestamp')
        batch_op.drop_index('idx_chat_session_id')

    # ### end Alembic commands ###
