"""auto_users_20260207_014646

Revision ID: a3411aa23ed5
Revises: 49ce8de66335
Create Date: 2026-02-07 01:46:47.650909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3411aa23ed5'
down_revision: Union[str, None] = '49ce8de66335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field_v2', sa.String(length=50), nullable=True))
        batch_op.drop_column('test_field_v1')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field_v1', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('test_field_v2')

    # ### end Alembic commands ###
