"""add_user_feedbacks_table

Revision ID: c6888baf88ee
Revises: d8e98a2cca21
Create Date: 2026-04-19 18:32:03.994238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6888baf88ee'
down_revision: Union[str, None] = 'd8e98a2cca21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('replied_by', sa.Integer(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('is_read_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['replied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedbacks', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_category', ['category'], unique=False)
        batch_op.create_index('ix_feedback_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedbacks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedbacks_user_id'))
        batch_op.drop_index('ix_feedback_status')
        batch_op.drop_index('ix_feedback_category')

    op.drop_table('user_feedbacks')
    # ### end Alembic commands ###
