"""auto_users_20260207_014139

Revision ID: d52ead50ed60
Revises: 642883ad2251
Create Date: 2026-02-07 01:41:40.345686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52ead50ed60'
down_revision: Union[str, None] = '642883ad2251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('debug_flag')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debug_flag', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
