"""auto_users_20260206_040255

Revision ID: d93c5c8e685a
Revises: 
Create Date: 2026-02-06 04:02:56.172335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93c5c8e685a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('users',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('debug_flag')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debug_flag', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
