"""auto_users_20260207_023406

Revision ID: e154f44cedda
Revises: 1e8bc8579a67
Create Date: 2026-02-07 02:34:07.172634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e154f44cedda'
down_revision: Union[str, None] = '1e8bc8579a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('final_test_renamed')

    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_test_renamed', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
